services:
    dmzx.countdownheader.listener:
        class: dmzx\countdownheader\event\listener
        arguments:
            - '@template'
            - '@config'
        tags:
            - { name: event.listener }
